import { 
  Trees, 
  Mountain, 
  Lightbulb, 
  Map, 
  Building2,
  Thermometer,
  CloudRain,
  Waves,
  Wind,
  Flame,
  Activity,
  UserGroup
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface LegendItem {
  color: string;
  label: string;
}

export interface Dataset {
  id: string;
  name: string;
  title: string;
  description: string;
  icon: LucideIcon;
  theme: "vegetation" | "terrain" | "lights" | "landcover" | "temperature" | "hydro" | "atmosphere" | "hazard";
  legend: LegendItem[];
  imageUrl?: string;
  category?: string;
  isExperimental?: boolean;
}

export const GLOBAL_DATASETS: Dataset[] = [
  {
    id: "vegetation",
    name: "Vegetation Index",
    title: "Vegetation Density",
    description: "MODIS Terra NDVI – Annual average. Highlights photosynthetic activity and forest health.",
    icon: Trees,
    theme: "vegetation",
    imageUrl: "https://storage.googleapis.com/ee-static/dataset-previews/MODIS_061_MOD13Q1.png",
    category: "Satellite Imagery",
    legend: [
      { color: "#1a1a1a", label: "No vegetation (< 0.1)" },
      { color: "#e5f5f9", label: "Sparse (0.1–0.2)" },
      { color: "#99d8c9", label: "Moderate (0.2–0.4)" },
      { color: "#2ca25f", label: "Dense (0.4–0.6)" },
      { color: "#006d2c", label: "Very dense (> 0.6)" },
    ],
  },
  {
    id: "terrain",
    name: "Global Elevation",
    title: "Terrain & Elevation",
    description: "NASA SRTM Digital Elevation Model (30 m). High-resolution topographical data.",
    icon: Mountain,
    theme: "terrain",
    imageUrl: "https://storage.googleapis.com/ee-static/dataset-previews/USGS_SRTMGL1_003.png",
    category: "Topography",
    legend: [
      { color: "#000033", label: "Depressions (< 0 m)" },
      { color: "#006400", label: "Lowlands (0–200 m)" },
      { color: "#228b22", label: "Plains (200–500 m)" },
      { color: "#00FFFF", label: "Hills (500–1000 m)" },
      { color: "#FFFF00", label: "Mountains (1000–2000 m)" },
      { color: "#FF8000", label: "High mountains (2000–4000 m)" },
      { color: "#FF0000", label: "Very high peaks (4000–6000 m)" },
      { color: "#800080", label: "Extreme peaks (> 6000 m)" },
    ],
  },
  {
    id: "nightlights",
    name: "Nighttime Lights",
    title: "Night Illumination",
    description: "NOAA VIIRS DNB (Gamma Enhanced). Measures artificial light emissions from Earth.",
    icon: Lightbulb,
    theme: "lights",
    imageUrl: "https://storage.googleapis.com/ee-static/dataset-previews/NOAA_VIIRS_DNB_MONTHLY_V1_VCMCFG.png",
    category: "Socio-Economic",
    legend: [
      { color: "#000000", label: "No activity (uninhabited)" },
      { color: "#1a0033", label: "Minimal (rural)" },
      { color: "#330066", label: "Low (small towns)" },
      { color: "#6600cc", label: "Medium (cities)" },
      { color: "#9933ff", label: "High (major cities)" },
      { color: "#cc66ff", label: "Very high (mega cities)" },
      { color: "#ffccff", label: "Extreme (urban centers)" },
      { color: "#ffffff", label: "Maximum (city cores)" },
    ],
  },
  {
    id: "landcover",
    name: "Land Cover",
    title: "Land Classification",
    description: "ESA WorldCover 2021 (10 m). Global map of land use and land cover types.",
    icon: Map,
    theme: "landcover",
    imageUrl: "https://storage.googleapis.com/ee-static/dataset-previews/ESA_WorldCover_v100.png",
    category: "Ecology",
    legend: [
      { color: "#006400", label: "Tree cover" },
      { color: "#ffbb22", label: "Shrubland" },
      { color: "#ffff4c", label: "Grassland" },
      { color: "#f096ff", label: "Cropland" },
      { color: "#fa0000", label: "Built-up" },
      { color: "#b4b4b4", label: "Bare / sparse vegetation" },
      { color: "#f0f0f0", label: "Snow and ice" },
      { color: "#0064c8", label: "Permanent water bodies" },
      { color: "#0096a0", label: "Herbaceous wetland" },
      { color: "#00cf75", label: "Mangroves" },
    ],
  },
  {
    id: "temperature",
    name: "Temperature",
    title: "Surface Temperature",
    description: "MODIS Terra LST – Summer 2023. Land surface temperature anomalies and trends.",
    icon: Thermometer,
    theme: "temperature",
    imageUrl: "https://storage.googleapis.com/ee-static/dataset-previews/MODIS_061_MOD11A1.png",
    category: "Climate",
    legend: [
      { color: "#000080", label: "Very cold (< 20 °C)" },
      { color: "#0000FF", label: "Cold (20–25 °C)" },
      { color: "#00FFFF", label: "Cool (25–30 °C)" },
      { color: "#00FF00", label: "Moderate (30–35 °C)" },
      { color: "#FFFF00", label: "Warm (35–40 °C)" },
      { color: "#FF8000", label: "Hot (40–45 °C)" },
      { color: "#FF0000", label: "Very hot (> 45 °C)" },
    ],
  },
  {
    id: "ndbi",
    name: "NDBI Analysis",
    title: "Built-up Index",
    description: "Normalized Difference Built-up Index. Highlights urban/built-up intensity.",
    icon: Building2,
    theme: "landcover",
    category: "Urban",
    legend: [
      { color: "#0000FF", label: "Water bodies" },
      { color: "#00FFFF", label: "Low reflectance" },
      { color: "#00FF00", label: "Vegetation" },
      { color: "#FFFF00", label: "Mixed/Bare" },
      { color: "#FFA500", label: "Built-up" },
      { color: "#FF0000", label: "Dense built-up" },
    ],
  },
  {
    id: "ndwi",
    name: "NDWI Analysis",
    title: "Water Index",
    description: "Normalized Difference Water Index. Highlights surface water and wet zones.",
    icon: Waves,
    theme: "hydro",
    category: "Hydrology",
    legend: [
      { color: "#8b4513", label: "Very dry / built-up" },
      { color: "#f4a460", label: "Low moisture" },
      { color: "#f0e68c", label: "Moderate moisture" },
      { color: "#87ceeb", label: "Wet soil / shallow water" },
      { color: "#1e90ff", label: "Water bodies" },
      { color: "#00008b", label: "Deep water" },
    ],
  },
  {
    id: "rainfall",
    name: "Global Rainfall",
    title: "Precipitation",
    description: "GPM IMERG Precipitation – Monthly mean. Monitors global weather patterns.",
    icon: CloudRain,
    theme: "atmosphere",
    imageUrl: "https://storage.googleapis.com/ee-static/dataset-previews/NASA_GPM_L3_IMERG_V06.png",
    category: "Climate",
    isExperimental: true,
    legend: [
      { color: "#f7fbff", label: "Dry (< 1 mm)" },
      { color: "#deebf7", label: "Light (1–5 mm)" },
      { color: "#c6dbef", label: "Moderate (5–10 mm)" },
      { color: "#9ecae1", label: "Heavy (10–20 mm)" },
      { color: "#6baed6", label: "Intense (> 20 mm)" },
    ],
  },
  {
    id: "ocean_temp",
    name: "Ocean Surface",
    title: "Sea Temperature",
    description: "MODIS Aqua SST. Sea surface temperature for marine ecosystem monitoring.",
    icon: Waves,
    theme: "hydro",
    imageUrl: "https://storage.googleapis.com/ee-static/dataset-previews/NASA_OCEANDATA_MODIS-Aqua_L3SMI_SST.png",
    category: "Oceanography",
    legend: [
      { color: "#053061", label: "Freezing (< 5 °C)" },
      { color: "#2166ac", label: "Cold (5–15 °C)" },
      { color: "#4393c3", label: "Cool (15–20 °C)" },
      { color: "#d1e5f0", label: "Pleasant (20–25 °C)" },
      { color: "#f4a582", label: "Warm (25–30 °C)" },
      { color: "#b2182b", label: "Tropical (> 30 °C)" },
    ],
  },
  {
    id: "wildfire_risk",
    name: "Wildfire Risk",
    title: "Burn Vulnerability",
    description: "MODIS Fire Risk Index. Derived from biomass dryness and temperature trends.",
    icon: Flame,
    theme: "hazard",
    imageUrl: "https://storage.googleapis.com/ee-static/dataset-previews/MODIS_006_MOD14A1.png",
    category: "Hazards",
    isExperimental: true,
    legend: [
      { color: "#ffffb2", label: "Low risk" },
      { color: "#fecc5c", label: "Moderate" },
      { color: "#fd8d3c", label: "High" },
      { color: "#f03b20", label: "Critical" },
      { color: "#bd0026", label: "Extreme" },
    ],
  },
  {
    id: "population",
    name: "Population Density",
    title: "Human Presence",
    description: "GPW v4 Population Density. Persons per square kilometer estimated for 2020.",
    icon: Activity,
    theme: "lights",
    imageUrl: "https://storage.googleapis.com/ee-static/dataset-previews/CIESIN_GPWv411_GPW_Population_Density.png",
    category: "Socio-Economic",
    legend: [
      { color: "#fcfbfd", label: "0–1 (Uninhabited)" },
      { color: "#efedf5", label: "1–5 (Remote)" },
      { color: "#dadaeb", label: "5–25 (Sparse)" },
      { color: "#bcbddc", label: "25–100 (Rural)" },
      { color: "#9e9ac8", label: "100–500 (Suburban)" },
      { color: "#756bb1", label: "500–1000 (Urban)" },
      { color: "#54278f", label: "1000+ (High Density)" },
    ],
  },
  {
    id: "worldcereal_models_v100",
    name: "WorldCereal Models",
    title: "ESA Crop Classification",
    description: "WorldCereal model-derived crop classification layer.",
    icon: Map,
    theme: "landcover",
    category: "Agriculture",
    isExperimental: true,
    legend: [
      { color: "#000000", label: "No crop" },
      { color: "#00ff00", label: "Crop class" },
    ],
  },
  {
    id: "worldcereal_markers_v100",
    name: "WorldCereal Markers",
    title: "Active Cropland Marker",
    description: "Active cropland marker layer from ESA WorldCereal.",
    icon: Trees,
    theme: "vegetation",
    category: "Agriculture",
    isExperimental: true,
    legend: [
      { color: "#000000", label: "Inactive" },
      { color: "#00bfff", label: "Active cropland" },
    ],
  },
  {
    id: "wapor_et_ratio",
    name: "WAPOR ET Ratio",
    title: "ETa/ETo Efficiency",
    description: "FAO WAPOR evapotranspiration ratio for water-use monitoring.",
    icon: Waves,
    theme: "hydro",
    category: "Water & Agriculture",
    isExperimental: true,
    legend: [
      { color: "#8b0000", label: "Low ratio" },
      { color: "#ffa500", label: "Moderate" },
      { color: "#00ff00", label: "High ratio" },
    ],
  },
  {
    id: "gfsad_cropland_extent",
    name: "GFSAD Cropland Extent",
    title: "Global Cropland Extent",
    description: "USGS global cropland extent / landcover map.",
    icon: Map,
    theme: "landcover",
    category: "Agriculture",
    legend: [
      { color: "#ff8c00", label: "Cropland" },
      { color: "#00a650", label: "Vegetated" },
      { color: "#000000", label: "Other" },
    ],
  },
  {
    id: "fao_drained_organic_soils",
    name: "FAO Drained Organic Soils",
    title: "Drained Organic Soil Area",
    description: "Latest drained organic soils map from FAO GHG products.",
    icon: Mountain,
    theme: "hazard",
    category: "Climate",
    isExperimental: true,
    legend: [
      { color: "#f7fcf5", label: "Low" },
      { color: "#74c476", label: "Medium" },
      { color: "#00441b", label: "High" },
    ],
  },
  {
    id: "forest_loss_drivers_wri_gdm",
    name: "Forest Loss Drivers",
    title: "Dominant Forest-Loss Driver",
    description: "Driver class map for forest-loss causation.",
    icon: Flame,
    theme: "hazard",
    category: "Ecology",
    isExperimental: true,
    legend: [
      { color: "#d7191c", label: "Shifting cultivation" },
      { color: "#2b83ba", label: "Wildfire" },
      { color: "#8073ac", label: "Other drivers" },
    ],
  },
  {
    id: "chirps_rainfall_anomaly",
    name: "CHIRPS Rainfall Anomaly",
    title: "Rainfall Deviation",
    description: "Recent rainfall anomaly against long-term CHIRPS baseline.",
    icon: CloudRain,
    theme: "atmosphere",
    category: "Climate",
    legend: [
      { color: "#8b0000", label: "Deficit" },
      { color: "#f7f7f7", label: "Near normal" },
      { color: "#08519c", label: "Surplus" },
    ],
  },
  {
    id: "gfs_forecast_panel",
    name: "GFS Forecast Panel",
    title: "24h Forecast Temperature",
    description: "NOAA GFS near-term 2m temperature forecast.",
    icon: Wind,
    theme: "atmosphere",
    category: "Weather",
    isExperimental: true,
    legend: [
      { color: "#313695", label: "Cool" },
      { color: "#fee090", label: "Mild" },
      { color: "#a50026", label: "Hot" },
    ],
  },
  {
    id: "soil_moisture_smap",
    name: "SMAP Soil Moisture",
    title: "Surface Soil Moisture",
    description: "NASA SMAP surface soil moisture composite.",
    icon: Waves,
    theme: "hydro",
    category: "Soil & Water",
    legend: [
      { color: "#f46d43", label: "Dry" },
      { color: "#abd9e9", label: "Moderate" },
      { color: "#2c7bb6", label: "Wet" },
    ],
  },
  {
    id: "spei_drought_index",
    name: "SPEI Drought Index",
    title: "SPEI 12-Month",
    description: "Standardized drought indicator from CSIC SPEI.",
    icon: Flame,
    theme: "hazard",
    category: "Drought",
    legend: [
      { color: "#8b0000", label: "Severe drought" },
      { color: "#fee08b", label: "Neutral" },
      { color: "#1a9850", label: "Wet" },
    ],
  },
  {
    id: "kbdi_drought_index",
    name: "KBDI Drought Index",
    title: "Keetch-Byram Index",
    description: "Fire-weather drought indicator (KBDI).",
    icon: Flame,
    theme: "hazard",
    category: "Drought",
    isExperimental: true,
    legend: [
      { color: "#313695", label: "Low" },
      { color: "#fee090", label: "Moderate" },
      { color: "#a50026", label: "Extreme" },
    ],
  },
  {
    id: "dynamic_land_cover_change",
    name: "Dynamic Land Cover Change",
    title: "Dynamic World Crops Probability",
    description: "Mean crop probability from Dynamic World observations.",
    icon: Trees,
    theme: "landcover",
    category: "Land Cover",
    isExperimental: true,
    legend: [
      { color: "#ffffff", label: "Low probability" },
      { color: "#fecc5c", label: "Medium" },
      { color: "#e31a1c", label: "High" },
    ],
  },
  {
    id: "era5_land_heat_stress",
    name: "ERA5 Land Heat Stress",
    title: "Mean 2m Temperature",
    description: "ERA5-Land hourly mean temperature for heat-stress analysis.",
    icon: Thermometer,
    theme: "temperature",
    category: "Heat",
    legend: [
      { color: "#313695", label: "Cool" },
      { color: "#fee08b", label: "Warm" },
      { color: "#a50026", label: "Severe heat" },
    ],
  },
  {
    id: "soilgrids_baseline",
    name: "SoilGrids Baseline",
    title: "Volumetric Soil Water Content",
    description: "Static SoilGrids baseline for shallow soil water content.",
    icon: Mountain,
    theme: "hydro",
    category: "Soil & Water",
    isExperimental: true,
    legend: [
      { color: "#440154", label: "Very low" },
      { color: "#21918c", label: "Moderate" },
      { color: "#fde725", label: "High" },
    ],
  },
  {
    id: "gpm_imerg_precip",
    name: "GPM IMERG Precipitation",
    title: "IMERG Mean Rainfall",
    description: "Mean precipitation from NASA GPM IMERG V07.",
    icon: CloudRain,
    theme: "atmosphere",
    category: "Weather",
    legend: [
      { color: "#f7fbff", label: "Low" },
      { color: "#6baed6", label: "Moderate" },
      { color: "#08306b", label: "Heavy" },
    ],
  }
];
